config/owasp/suppressions.xml

Suppressing the transitive dependency vulnerability on dom4j.

supressing the transitive dependency of springboot

---

README.md
web.config

Fixing jar name reference

---

config/owasp/suppressions.xml

Suppressing dep warning

---

config/owasp/suppressions.xml

Suppressing owasp vulnerability

---

src/main/java/uk/gov/hmcts/reform/professionalapi/infrastructure/controllers/request/SuperuserPbaAccountValidator.java

fixing sonar violation

---

infrastructure/output.tf

fixing the vault name issue

---

infrastructure/main.tf
infrastructure/output.tf

This should fix the AAT build. My bad...
https://tools.hmcts.net/jira/browse/RDCC-73
Restored Terraform configuration that was removed by #16 
```
[ ] Yes
[X] No
```

Restore removed sections of Terraform config

---

infrastructure/main.tf

According to the CNP team, this fixes the issue
https://tools.hmcts.net/jira/browse/RDCC-73
```
[ ] Yes
[X] No
```

Update Terraforn azurerm backend provider to 1.22.0

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/OrganisationRetrieveTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrganisationWithPaymentAccountTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/OrganisationController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ContactInformationResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/DxAddressResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationsDetailResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/PbaAccountResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/SuperUserResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationService.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationServiceImplTest.java

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1034&projectKey=RDCC&view=detail&selectedIssue=RDCC-108
RDCC -164
Retrieve Organisation Details related changes committed.
```
[ ] Yes
[x ] No
```

RDCC-108-164 code changes committed

---

.githooks/pre-push

https://tools.hmcts.net/jira/browse/RDCC-199
```
[ ] Yes
[X] No
```

Fix git hook so it actually runs integration tests

---

Jenkinsfile_CNP
Jenkinsfile_parameterized

https://tools.hmcts.net/jira/browse/RDCC-200
```
[ ] Yes
[X] No
```

RDCC-200: Use Tim J's suggestion to try and get green builds without deploying to prod

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-211
updated dependency to fix jenkins build
```
[ ] Yes
[x] No
```

RDCC-211 updated jackson-databind dependency to fix Jenkins build

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/SuperUserResponse.java

master build is failing with  few functional test cases issues so handling the code with some null check
```
[ ] Yes
[X ] No
```

RDCC-prod-build-fix: code fixed to handle null pointer exception

---

src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/SecurityConfiguration.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RDCC-276
Code committed to remove authorization for legacy endpoint
```
[ ] Yes
[X ] No
```

RDCC-276:Code committed to remove authorization for legacy endpoint

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/LegacyPbaController.java

https://tools.hmcts.net/jira/projects/RDCC/issues/RDCC-276
Removed Authorization header from swagger doc for legacy endpoint.
```
[ ] Yes
[X ] No
```

Rdcc 276 legacy pba

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/PaymentAccountRetrieveByEmailTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindPaymentAccountsByEmailTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/ApplicationConfiguration.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/LegacyPbaAccountServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/PaymentAccountServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/PbaAccountUtil.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/professionalapi/service/PaymentAccountServiceTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/LegacyPbaAccountServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/utils/PbaAccountUtilTest.java

https://tools.hmcts.net/jira/projects/RDCC/issues/RDCC-282
Relationship of PBAs and Users with Organisation
```
[ ] Yes
[ X] No
```

Rdcc pba by email

---

Jenkinsfile_CNP

reverting Jenkins_CNP file

---

Jenkinsfile_nightly
security.sh

Nightly build fix
```
[ ] Yes
[ X] No
```

Fixing Nightly build

---

Jenkinsfile_nightly
build.gradle
config/owasp/suppressions.xml
security.sh

Change is to copy the output of the security scan into reports folder
```
[ ] Yes
[X ] No
```

Nightly build fix

---

infrastructure/main.tf

This is to fix the build. This is as part of the recent changes to jenkins library.
```
[ ] Yes
[ X] No
```

Need to add subscription as part of jenkins lib chsanges

---

infrastructure/main.tf
security.sh

Attempt to fix security scan - as per suggestions from Satya
```
[ ] Yes
[ X] No
```

Security scan issue

---

security.sh

Creating the functional-output folder, as it is needed by the security scan
```
[ ] Yes
[ X] No
```

Adding create directory command

---

.gitignore
functional-output/.gitignore
security.sh

Nightly build configuration
```
[ ] Yes
[ X] No
```

Securitychanges

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/RDCC-408
enabling build pipeline to production
```
[ ] Yes
[ X] No
```

enabling build pipeline to production

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
src/main/resources/application.yaml

No JIRA
Added the xui service name in the authorised service list and fixed the get users for external end point
```
[ ] Yes
[ X] No
```

Get ext users fix

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateNewUserWithRolesTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrganisationWithContactInformationDxAddress.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrganisationWithPaymentAccountForSuperuserTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindPaymentAccountsByEmailTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUserByEmailTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RoleBasedAccessForUpdateTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/UpdateOrganisationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/ErrorConstants.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/ExceptionMapper.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/OrganisationCreationRequest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/OrganisationCreationRequestValidator.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/UserCreationRequestValidator.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/GetUserProfileResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ProfessionalUsersResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/domain/Organisation.java
src/main/java/uk/gov/hmcts/reform/professionalapi/persistence/OrganisationRepository.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/PbaAccountUtil.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/utils/OrganisationFixtures.java

https://tools.hmcts.net/jira/browse/RDCC-394
https://tools.hmcts.net/jira/browse/RDCC-398
https://tools.hmcts.net/jira/browse/RDCC-275
https://tools.hmcts.net/jira/browse/RDCC-315
This PR includes:
- Company Number LENGTH validation
- Company Number DUPLICATE validation
- GET all Users Response includes Idam Status Code & Message
- UPDATE Organisation takes "organisationStatus" case insensitive
- Duplicate roles for New Users will not be persisted 
```
[ ] Yes
[X] No
```

RDCC-394/398/315/275 Company Number validation, Idam Status/Message, Organisation Status insensitive, Duplicate User Roles

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java

https://tools.hmcts.net/jira/browse/RDCC-315
duplicate user roles FIX
```
[ ] Yes
[X] No
```

Rdcc 315 - duplicate user roles FIX

---

src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateNewUserWithRolesTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/OrganisationCreationRequestValidator.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/controller/request/OrganisationCreationRequestValidatorTest.java

https://tools.hmcts.net/jira/browse/RDCC-434
```
[ ] Yes
[X] No
```

RDCC-434 changed status code to 400

---

infrastructure/main.tf

CCD vault fix
```
[ ] Yes
[x] No
```

CCD vault fix

---

infrastructure/main.tf

Removing duplicate entry of CCD_URL vault
```
[ ] Yes
[x] No
```

Removing duplicate entry of CCD_URL vault

---

src/main/resources/db/migration/V6_6__adding_ccd_roles_enum.sql

https://tools.hmcts.net/jira/browse/RDCC-439
add new CCD roles.
```
[ ] Yes
[X ] No
```

RDCC-Roles-Fix :New Roles added

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AddNewUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/EndpointSecurityTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/LegacyPbaNumbersRetrieveByUserEmailTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/OrganisationCreationsTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/OrganisationRetrieveTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/PaymentAccountRetrieveByEmailTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/UpdateOrganisationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/UserEmailSearchTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/functionalTest/resources/application-functional.yaml
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateMinimalOrganisationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/ExceptionMapper.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/UserCreationRequest.java

Functional test cases
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No

Prd functional fix

---

Jenkinsfile_CNP
src/functionalTest/resources/application-functional.yaml
src/main/resources/application.yaml

aat urls updated for functional test cases
```
[ ] Yes
[X ] No
```

aat urls updated for functional test cases

---

Jenkinsfile_CNP
src/functionalTest/resources/application-functional.yaml
src/main/resources/application.yaml

Demo-to-master merge
```
[ ] Yes
[X ] No
```

merge to-Demo 

---

Jenkinsfile_CNP

Disabled AKS staging.
```
[ ] Yes
[X ] No
```

Ignoring AKS staging

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationServiceImplTest.java

RDCC-463
Code committed for to fix prof perftest issue
```
[ ] Yes
[ X] No
```

 Code committed for to fix prof perftest issue

---

Jenkinsfile_CNP

Disabling AKS in Demo
```
[ ] Yes
[X ] No
```

Final rel 2

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/JurisdictionServiceImpl.java

RDCC-445 change error message and code when ccd is down
RDCC-445 change error message and code when ccd is down
```
[ ] Yes
[x] No
```

RDCC-445 change error message and code when ccd is down

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-442
```
[ ] Yes
[X] No
```

RDCC-442 adding unit test coverage threshold

---

src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateMinimalOrganisationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateNewUserWithRolesTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrganisationWithPaymentAccountForSuperuserTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/OrganisationCreationRequestValidator.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/ProfessionalUserReqValidator.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/ProfessionalUserReqValidatorTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/controller/request/OrganisationCreationRequestValidatorTest.java

https://tools.hmcts.net/jira/browse/RDCC-497
```
[ ] Yes
[ ] No
```

Rdcc 497 - email validation fix

---

Jenkinsfile_CNP
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RDCC-561
Add  FR team service name in authorized service list.
```
[ ] Yes
[ X] No
```

RDCC-561: fr team service name added in the service authorisation list

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ModifyRolesForUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/idam/IdamClient.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/OrganisationCreationRequestValidator.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/IdamStatus.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ProfessionalUsersResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/persistence/ProfessionalUserRepository.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/ProfessionalUserService.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/JsonFeignResponseHelper.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtil.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/ProfessionalExternalUserControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/controller/request/OrganisationCreationRequestValidatorTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/ProfessionalUserServiceTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/utils/JsonFeignResponseHelperTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/utils/RefDataUtilTest.java

https://tools.hmcts.net/jira/browse/RDCC-297
Pagination for GET Users Endpoint
```
[ ] Yes
[X] No
```

RDCC 476/297 - Pagination

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/RDCC-478
```
[ ] Yes
[ ] No
```

RDCC-478 - disable AAT deploy

---

charts/rd-professional-api/Chart.yaml
charts/rd-professional-api/values.yaml

Add missing ingress host

---

build.gradle

Reverting version number to fix jenkins master build

---

README.md
src/contractTest/java/uk/gov/hmcts/reform/professionalapi/sample/IdamConsumerTest.java

RDCC-636 fixing type-o in README

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AddNewUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersStatusByEmailTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ModifyRolesForUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ModifyStatusForUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/RetrievePaymentAccountTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/UpdateStatusForUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/UserRolesTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/functionalTest/resources/application-functional.yaml
src/main/resources/application.yaml
src/main/resources/db/migration/V6_10__adding_new_user_roles_for_ccd_view.sql

https://tools.hmcts.net/jira/browse/RDCC-677
Creation of first user with default set of FPLA and CCD roles
```
[ ] Yes
[X] No
```

Rdcc 677 v1

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/UserRolesTest.java

https://tools.hmcts.net/confluence/display/RTRD/Creation+of+user+with+a+given+set+of+FPLA+and+IAC+roles
FPLA roles
```
[ ] Yes
[X] No
```

QA requested changes

---

Jenkinsfile_CNP

RDCC-737
doing itch changes for PRD.
```
[ ] Yes
[ X] No
```

Rdcc 737 v1

---

build.gradle
charts/rd-professional-api/Chart.yaml
charts/rd-professional-api/values.preview.template.yaml
config/owasp/suppressions.xml
src/main/resources/application.yaml

RDCC-741
moving new services to master for fpl and ia
```
[ ] Yes
[ X] No
```

Moving Services: bumpup jackson version

---

charts/rd-professional-api/Chart.yaml
src/functionalTest/resources/application-functional.yaml
src/main/resources/application.yaml

config: changed the chart version

---

Jenkinsfile_CNP
charts/rd-professional-api/Chart.yaml

Rd prof ithc

---

charts/rd-professional-api/values.perftest.template.yaml
infrastructure/ithc.tfvars
infrastructure/perftest.tfvars

RDCC-727
adding the changes for perf and ithc
```
[ ] Yes
[ X] No
```

adding ithc and perftest.tfvars to make capacity 1

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersStatusByEmailTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java

https://tools.hmcts.net/jira/browse/RDCC-747
```
[ ] Yes
[ x] No
```

RDCC-747_2 updated endpoints

---

charts/rd-professional-api/values.ithc.template.yaml
charts/rd-professional-api/values.perftest.template.yaml
infrastructure/ithc.tfvars
infrastructure/perftest.tfvars

RDCC-227
adding ithc and perftest.tfvars to make capacity 1 and charts
```
[ ] Yes
[ X] No
```

adding ithc and perftest.tfvars to make capacity 1 and charts

---

src/main/resources/application.yaml

Iac  service name changes in application yaml file
```
[ ] Yes
[ X] No
```

iac: service name changes

---

src/main/resources/db/migration/V6_11__delete_duplicate_jurisdiction_id.sql

RDCC-751, RDCC-745
Removing duplicate jurisdiction and adding two more CCD roles for SSCS
```
[ ] Yes
[X] No
```

RDCC-571 RDCC-745 Removing duplicate jurisdiction and adding two more CCD roles for SSCS

---

README.md

test: perf test check

---

README.md

NA
test: perftest readme update
No

test: perftest readme update

---

README.md
config/owasp/suppressions.xml

NA
fix: Phantom suppression
No

fix: Phantom suppression

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/UserRolesTest.java
src/functionalTest/resources/application-functional.yaml

RDCC-744-V1
verify super user sscs roles for super user
```
[ ] Yes
[ X] No
```

Rdcc 744 v1

---

charts/rd-professional-api/values.yaml
src/main/resources/bootstrap.yaml

NA
fix: added perf test secrets
No

fix: added perf test secrets

---

build.gradle

Fix sonar changes suggested by DevOps
```
[ ] Yes
[X] No
```

Fixing sonar changes

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ModifyRolesForUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ModifyStatusForUserTest.java

Merge master Rel 3.0.0 to demo
```
[ ] Yes
[X] No
```

Merge master Rel 3.0.0 to demo

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersStatusByEmailTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/OrganisationRetrieveTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/RetrievePaymentAccountTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/UserRolesTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/DeleteUserRoleIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/ModifyUserRoleIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java

Adding pui-case-manager role to list of permitted roles 
for 
Endpoint GET /refdata/external/v1/organisations
https://tools.hmcts.net/jira/browse/RDCC-861

RDCC 861 - adding pui-case-manager role

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RDCC-790
fix: removed s2s values with dummy values
No

fix: removed s2s values with dummy values

---

Jenkinsfile_CNP
Jenkinsfile_nightly
build.gradle
src/contractTest/java/uk/gov/hmcts/reform/professionalapi/sample/IdamConsumerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/UpdateOrganisationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/LegacyPbaController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/WelcomeController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/CcdErrorMessageResolver.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/ErrorConstants.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/domain/UserProfileUpdatedData.java
src/main/java/uk/gov/hmcts/reform/professionalapi/security/JwtAccessTokenDecoder.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/JurisdictionServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtil.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/CcdErrorMessageResolver.java
src/test/java/uk/gov/hmcts/reform/professionalapi/security/JwtAccessTokenDecoderTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/ProfessionalUserServiceTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/JurisdictionServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/utils/RefDataUtilTest.java

RDCC-915
RDCC-915 Abort CCD when error and updated error messages
```
[ ] Yes
[X] No
```

RDCC-915 Abort CCD when error and updated error messages

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AddNewUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ModifyRolesForUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/OrganisationRetrieveTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/RetrievePaymentAccountTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateNewUserWithRolesTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/domain/ContactInformation.java
src/main/java/uk/gov/hmcts/reform/professionalapi/domain/Organisation.java
src/main/java/uk/gov/hmcts/reform/professionalapi/persistence/OrganisationRepository.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationService.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/ProfessionalUserService.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/OrganisationInternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/entities/ContactInformationTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/PaymentAccountServiceTest.java

https://tools.hmcts.net/jira/browse/RDCC-899

retrofitting performance improvement for getting all orgs, to master

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/OrganisationRetrieveTest.java

RDCC-958
changing the dxNumber 
```
[ ] Yes
[ X] No
```

The dxNumber size is verify.

---

src/test/java/uk/gov/hmcts/reform/professionalapi/helper/BaseRepository.java
src/test/java/uk/gov/hmcts/reform/professionalapi/repository/ContactInformationRepositoryTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/repository/DxAddressRepositoryTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/repository/OrganisationRepositoryTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/repository/PaymentAccountRepositoryTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/repository/PrdEnumRepositoryTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/repository/ProfessionalUserRepositoryTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/repository/UserAccountMapRepositoryTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/repository/UserAttributeRepositoryTest.java
src/test/resources/application.yaml

Bringing changes from PR:https://github.com/hmcts/rd-professional-api/pull/480 and https://github.com/hmcts/rd-professional-api/pull/483 into Demo

RDCC-1058: bringing in changes from Master for ignored repository tests

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateMinimalOrganisationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateNewUserWithRolesTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrganisationWithContactInformationDxAddress.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrganisationWithPaymentAccountForSuperuserTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrganisationWithPaymentAccountTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/DeleteUserRoleIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/EditPaymentAccountsTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindPaymentAccountsByEmailTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUserByEmailTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/LegacyPaymentAccountsByEmailTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/ModifyUserRoleIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/ModifyUserStatusIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RoleBasedAccessForUpdateTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/UpdateOrganisationTest.java

Moving changes from https://github.com/hmcts/rd-professional-api/pull/471 to Demo

RDCC-863: moving changes from Master to Demo

---

build.gradle
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java

added dependency suppressions for embedded tomcat
```
[ ] Yes
[X] No
```

fix : added dependency suppressions for embedded tomcat

---

build.gradle
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ReInviteUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/functionalTest/resources/application-functional.yaml
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateMinimalOrganisationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/LegacyPaymentAccountsByEmailTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/ReInviteUserIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
src/integrationTest/resources/application.yml
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/NewUserCreationRequest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/UserProfileCreationRequest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/NewUserResponse.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/SuperControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/NewUserCreationRequestTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/UserProfileCreationRequestTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidatorTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/helper/OrganisationFixtures.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtilTest.java

https://tools.hmcts.net/jira/browse/RDCC-901
feat: (RDCC-901) Merging Reinvite functionality to master
```
[ ] Yes
[X] No
```

feat: (RDCC-901) Merging Reinvite functionality to master

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/LegacyPbaController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/PbaEditRequest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ProfessionalUsersEntityResponse.java

https://tools.hmcts.net/jira/browse/RDCC-969
**THIS IS THE PR FOR CHANGES TO MASTER**
The changes were approved and tested in this PR: https://github.com/hmcts/rd-professional-api/pull/503
- The Request and Response payloads for all APIs should be populated
- The description of all APIs should be consistent with their meaning
- All possible error codes and error descriptions are present
```
[ ] Yes
[x] No
```

RDCC-969, MASTER: Update Swagger Descriptions for APIs

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ProfessionalUsersEntityResponse.java

RDCC-969
reverting the extra json property from response.
```
[ ] Yes
[X ] No
```

feat:reverting the extra json property from response.

---

src/functionalTest/resources/application-functional.yaml
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ProfessionalUsersEntityResponse.java

RDCC-1309
```
[ ] Yes
[ X] No
```

feat: Test_URL pointing to AAT instead of localhost

---

src/functionalTest/resources/application-functional.yaml
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/LegacyPbaController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/PbaEditRequest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ProfessionalUsersEntityResponse.java

RDCC-969
reverting the swagger docs changes in the master
```
[ ] Yes
[X ] No
```

feat:reverting the swagger docs changes in the master

---

src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/JacksonConfiguration.java

fix for accepting extra json fields
```
[ ] Yes
[X] No
```

fix : fix for accepting extra json fields

---

build.gradle
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AddNewUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateNewUserWithRolesTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/DeleteUserRoleIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUserByEmailTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/ModifyUserRoleIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/ModifyUserStatusIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/LegacyPbaController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/ProfessionalUserService.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/JsonFeignResponseUtil.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/util/JsonFeignResponseUtilTest.java

Pulling changes from these PR's (Master) to Demo:
```
[ ] Yes
[x] No
```

Pulling changes from RDCC-1234, 969 & 1040 (Master) To Demo

---

Jenkinsfile_CNP
Jenkinsfile_parameterized

https://tools.hmcts.net/jira/browse/RDCC-1440
removing installCharts() from Jenkinsfile(s)
```
[ ] Yes
[x] No
```

RDCC-1440, Master: removing installCharts() from Jenkinsfile(s)

---

audit.json
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtilTest.java

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-1464
changes for nightly build and Mutation Test
Does this PR introduce a breaking change? (check one with "x")
No

refactor: changes for nightly build and Mutation Test

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserControllerTest.java

RDCC-1429
adding caller user status active or not for get user roles api
```
[ ] Yes
[ X] No
```

feat: adding caller user status active or not for get user roles api

---

src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateMinimalOrganisationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrganisationWithContactInformationDxAddress.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrganisationWithPaymentAccountForSuperuserTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/EditPaymentAccountsTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidator.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ContactInformationResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponse.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidatorTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/ContactInformationResponseTest.java

Reverts hmcts/rd-professional-api#592

Revert "feat: validation for dx address is modified and code committed."

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/ProfessionalUserService.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtil.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtilTest.java

https://tools.hmcts.net/jira/browse/RDCC-1439
_FPLA Requirement - Retrieve list of all users of organisation without roles_
```
[ ] Yes
[x] No
```

RDCC-1439, Demo: Retrieve list of all users of organisation without roles

---

charts/rd-professional-api/Chart.yaml

Reducing chart version in Demo to match flux version

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AddNewUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationByOrgIdTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/UserRolesTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/idam/IdamOpenIdClient.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImplTest.java

RDCC-1538
get roles by user based on the flag  for internal api
```
[ ] Yes
[X ] No
```

feat: get roles by user based on the flag  for internal api

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ProfessionalUsersEntityResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ProfessionalUsersEntityResponseWithoutRoles.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtil.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtilTest.java

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-1589
feat:RDCC-1589 Assign access- add organisationIdenitifier in get user response
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No

feat:RDCC-1589 Assign access- add organisationIdenitifier in get user response

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/PbaEditRequest.java

RDCC-1041
updated json payload to support edit pbas by exui
```
[ ] Yes
[X ] No
```

feat:updated json payload

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/PbaEditRequest.java

RDCC-1641
edit pbas fix
```
[ ] Yes
[X] No
```

feat:editPbas issue fix in prod

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/PbaEditRequest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImplTest.java

RDCC-1041
junit fix for sonar qube
```
[ ] Yes
[X ] No
```

Pbs prod fix

---

src/integrationTest/resources/application.yml
src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/FeignInterceptorConfiguration.java
src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/resolver/OrganisationIdArgumentResolver.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/WelcomeController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/ExceptionMapper.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/LogAndSuppressRequestRejectedExceptionFilter.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/UserCreationRequestValidator.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationIdentifierValidatorImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationStatusValidatorImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/JurisdictionServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/UserAccountMapServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtil.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtilTest.java

**JIRA link (if applicable)**
https://tools.hmcts.net/jira/browse/RDCC-1582
**Change description**
Bringing changes from: https://github.com/hmcts/rd-professional-api/pull/639
```
[ ] Yes
[x] No
```

RDCC-1582, Demo: Adding component name to all application logs

---

charts/rd-professional-api/values.preview.template.yaml
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ModifyRolesForUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ModifyStatusForUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationByOrgIdTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateMinimalOrganisationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrganisationWithContactInformationDxAddress.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/ModifyUserRoleIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/ModifyUserStatusIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidator.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ContactInformationResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/domain/ModifyUserRolesResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/ProfessionalUserService.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtil.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/SuperControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/ContactInformationResponseTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/domain/ModifyUserRolesResponseTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtilTest.java

…master from demo
RDCC-1693
feat: RDCC-1693 Production release for modify role response and dxaddress issues
```
[ ] Yes
[X] No
```

feat: RDCC-1693 Production release for modify role response and dxaddress issues

---

config/owasp/suppressions.xml

Suppressing new vulnerabilities blocking master build pipeline
```
[ ] Yes
[x] No
```

RDCC-1684: suppressing new vulnerabilities

---

config/owasp/suppressions.xml

suppressing new vulnerability to unblock Master Build
```
[ ] Yes
[x] No
```

RDCC-1684: suppressing new vulnerability

---

src/integrationTest/resources/application.yml
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/WelcomeController.java

https://tools.hmcts.net/jira/browse/RDCC-1582
Making minor changes to bring latest changes to Demo Pod
```
[ ] Yes
[x] No
```

RDCC-1582: Adding component name to all application logs

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/OrganisationRetrieveTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/idam/IdamOpenIdClient.java

https://tools.hmcts.net/jira/browse/RDCC-1701
fix: functional test performance improvement
No

fix: functional test performance improvement

---

build.gradle
src/main/resources/application.yaml

RDCC-1670 Merge master to demo
RDCC-1670 Merge master to demo
```
[ ] Yes
[X] No
```

RDCC-1670 Merge master to demo

---

audit.json
src/main/resources/application.yaml

N/A
Nightly Build Fix
```
[ ] Yes
[x] No
```

PRD Nightly Build Fix

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-1778
Build(deps): Bumps ups flyway and Spring
No

Build(deps): Bumps ups flyway and Spring

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-1778
Build(deps): Bumps ups flyway
NO

Build(deps): Bumps ups flyway

---

infrastructure/state.tf

NA
Update TF version to v12.8 to match Core Infra state version
```
[ ] Yes
[ ] No
```

Update TF version to match the core infra version

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveMinimalOrganisationsInfoTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/functionalTest/resources/application-functional.yaml
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveMinimalOrganisationsInfoIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/integrationTest/resources/application.yml
src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/FeatureConditionEvaluation.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidator.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ContactInformationResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/ContactInformationResponseWithDxAddress.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/DxAddressResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationMinimalInfoResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidatorTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/ContactInformationResponseTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/ContactInformationResponseWithDxAddressTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationMinimalInfoResponseTest.java

https://tools.hmcts.net/jira/browse/RDCC-1706
Bringing changes from: https://github.com/hmcts/rd-professional-api/pull/694
```
[ ] Yes
[x] No
```

RDCC-1706, AAC 4.0: Bringing feature changes from Master to Demo

---

charts/rd-professional-api/Chart.yaml
charts/rd-professional-api/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/RDCC-1748
fix:removed instrumentation key from values preview.yaml
No

fix:removed instrumentation key from values preview.yaml

---

infrastructure/state.tf
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveMinimalOrganisationsInfoTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveMinimalOrganisationsInfoIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java

terraform changes from Master & AAC Description changes
```
[ ] Yes
[x] No
```

RDCC-1706: terraform changes from Master & AAC Description changes

---

audit.json
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveMinimalOrganisationsInfoTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveMinimalOrganisationsInfoIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java

Fixing Nightly Build & API/Error Description changes
```
[ ] Yes
[x] No
```

RDCC-1706: Fixing Nightly Build & API/Error Description changes

---

src/functionalTest/resources/application-functional.yaml

RDCC-1808
Fixing the functional.yaml
```
[ ] Yes
[X] No
```

RDCC-1808 fix functional test cases

---

Jenkinsfile_nightly

feat:nightly build fix
```
[ ] Yes
[X ] No
```

feat:nightly build fix

---

build.gradle

(RDCC-1876)
This PR will cover all bump ups in rd-professional
```
[ ] Yes
[X ] No
```

Bump up: rd-professional bump ups(RDCC-1876)

---

Jenkinsfile_nightly
build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/KeyGenUtil.java

RDCC=1876
This PR coveres the bump up version changes for rd-prof
```
[ ] Yes
[ X] No
```

Bump : Bump up jar versions(RDCC-1876)

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/DeleteOrganisationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/OrganisationCreationsTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/OrganisationRetrieveTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/RetrievePaymentAccountTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/UserEmailSearchTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrganisationWithContactInformationDxAddress.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUserByEmailTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java

[RDCC-1894](https://tools.hmcts.net/jira/browse/RDCC-1894)
Converting the following Functional Tests (identified in [RDCC-1894](https://tools.hmcts.net/jira/browse/RDCC-1894)) to Integration Tests:
```
[ ] Yes
[x] No
```

RDCC-1894: Convert Functional Tests to Integration Tests

---

src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/PaymentAccountServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/PaymentAccountServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-1870
feat: editpbas issue fixing
```
[ ] Yes
[ X] No
```

feat: editpbas issue fixing

---

src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/PaymentAccountServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/PaymentAccountServiceImplTest.java

feat: loggers adding for Edit pbas issue
```
[ ] Yes
[ X] No
```

Edit pbas issue

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RDCC-1934
```
[ ] Yes
[X] No
```

Delete secrets to create later

---

charts/rd-professional-api/Chart.yaml
charts/rd-professional-api/requirements.yaml
charts/rd-professional-api/values.yaml
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AddNewUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/DeleteOrganisationTest.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RDCC-2020 & https://tools.hmcts.net/jira/browse/RDCC-2031
Updating java chart version, refactoring commonly failing functional tests to integration or removing if already covered
```
[ ] Yes
[X] No
```

Updating java chart version - Master

---

Jenkinsfile_CNP
build.gradle

TA-24: Enable Pact Provider Tests in Jenkins

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java

Commenting out non-pui roles for super user
```
[ ] Yes
[x] No
```

fix: Functional Test changes: Commenting out non-pui roles for super user

---

build.gradle
charts/rd-professional-api/Chart.yaml
charts/rd-professional-api/requirements.yaml
charts/rd-professional-api/values.yaml
src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalExternalControllerProviderTest.java
src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalExternalControllerProviderTestConfiguration.java
src/contractTest/java/uk/gov/hmcts/reform/professionalapi/sample/IdamConsumerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AddNewUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/DeleteOrganisationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/EditPbaTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/EndpointSecurityTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersStatusByEmailTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ModifyRolesForUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ModifyStatusForUserTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/OrganisationCreationsTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/OrganisationRetrieveTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveMinimalOrganisationsInfoTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationByOrgIdTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/RetrievePaymentAccountTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/UpdateOrganisationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/UserRolesTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/idam/IdamOpenIdClient.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/RDCC-2020
Bringing changes from Master
```
[ ] Yes
[x] No
```

RDCC-2020, PerfTest: Bringing changes from Master

---

Jenkinsfile_CNP
src/contractTest/resources/application-contract.yaml

TA-24: Fix Pact test classpath issue

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/RDCC-2073
```
[ ] Yes
[X] No
```

Add method call to sync branches

---

build.gradle

RDCC 2017
This PR addresses all the Jar bump up versions which are created by bot
```
[ ] Yes
[ X] No
```

Bump : RDCC2017 Bump up Jar versions

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-2143
```
[ ] Yes
[x] No
```

Fix: Fixing the CVE 2020-8908

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalExternalUserFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/idam/IdamOpenIdClient.java

Adding retry to IDAM Create User call
```
[ ] Yes
[x] No
```

Fix: Adding retry to IDAM Create User call

---

README.md
audit.json
charts/rd-professional-api/Chart.yaml
charts/rd-professional-api/requirements.yaml

JIRA link
https://tools.hmcts.net/jira/browse/RDCC-2462
Security scan reported issue fix
```
[ ] Yes
[x] No
```

build: Security scan reported issue fix

---

charts/rd-professional-api/Chart.yaml
charts/rd-professional-api/values.preview.template.yaml
charts/rd-professional-api/values.yaml
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/RDCC-2505
```
[ ] Yes
[X] No
```

Update app insights secret key name

---

src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/DeleteOrganisationIntTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveMinimalOrganisationsInfoIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/LaunchDarklyConfiguration.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/FeatureToggleServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/FeatureToggleServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-2573
Remove launch darkly flags from PRD application
```
[ ] Yes
[X] No
```

fix: Remove launch darkly flags from PRD application

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-1985
removing unwanted suppressions
```
[ ] Yes
[x] No
```

RDCC-1985: removing unwanted suppressions

---

src/main/resources/application.yaml

RDCC-2632 added hikari configuration
RDCC-2632 added hikari configuration
```
[ ] Yes
[ ] No
```

fix:RDCC-2632 added hikari configuration

---

audit.json
src/main/java/uk/gov/hmcts/reform/professionalapi/util/JsonFeignResponseUtil.java

NA
(fix): Updating the zap security audit.json
```
[ ] Yes
[x] No
```

(fix): Updating the zap security audit.json

---

charts/rd-professional-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-2746
Helm chat version update
```
[ ] Yes
[X ] No
```

Rdcc 2746 helm upgrade

---

audit.json

https://tools.hmcts.net/jira/browse/RDCC-2770
Security Scan Fix: adding entries to audit.json
```
[ ] Yes
[x] No
```

RDCC-2770: Security Scan Fix - adding entries to audit.json

---

src/test/java/uk/gov/hmcts/reform/professionalapi/controller/SuperControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerTest.java

Adding additional Unit Tests for getUserEmail()
```
[ ] Yes
[x] No
```

Fix: Adding additional Unit Tests for getUserEmail()

---

build.gradle

upgarded spring boot version from 2.4.5 to 2.4.6

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/RDCC-2970
Update Jenkins nightly file to generate the serenity report
```
[ ] Yes
[X] No
```

RDCC-2970- Update Jenkins nightly file to generate the serenity report

---

security.sh

updated the order of command in security.sh to fixed security scan

---

src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindPaymentAccountsByEmailTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/JsonFeignResponseUtil.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtil.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponseTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtilTest.java

RDCC-3033
RDCC-3033 handling 500 request responses
```
[ ] Yes
[X] No
```

RDCC-3033 handling 500 request responses

---

build.gradle

RDCC-3150
This change is to remove the Bintray reference
```
[ ] Yes
[ X] No
```

fix: Remove bintray reference(RDCC-3150)

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/PaymentAccountValidator.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/UserAttributeServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/advice/ExceptionMapperTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerTest.java

https://tools.hmcts.net/jira/browse/RDCC-3168
Addressing `Sonar` Issues in Master
```
[ ] Yes
[x] No
```

RDCC-3168: Addressing Sonar Issues in Master

---

charts/rd-professional-api/Chart.yaml
deletescript/sql/delete-functional-test-data.sql

https://tools.hmcts.net/jira/browse/RDCC-3205
PRD API - Update delete script in Jenkins nightly job
```
[ ] Yes
[X] No
```

RDCC-3205 - PRD API - Update delete script in Jenkins nightly job

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-3237
Fix CVE issue : CVE-2021-28170
```
[ ] Yes
[X] No
```

RDCC-3237 - Fix CVE issue : CVE-2021-28170, CVE-2021-22119

---

audit.json

N/A
Fixing Nightly Build (Security Scan Issue): Adding entries to audit.json
```
[ ] Yes
[x] No
```

Fixing Nightly Build (Security Scan Issue): Adding entries to audit.json

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-3254
Suppressed CVE-2020-23171
```
[ ] Yes
[X] No
```

RDCC-3254 - Suppressed CVE-2020-23171

---

security.sh

https://tools.hmcts.net/jira/browse/RDCC-3239
Fix Security scan issue
```
[ ] Yes
[X] No
```

RDCC-3239- Fix Security scan issue

---

audit.json

Nightly Build Fix: Adding entries to audit.json
```
[ ] Yes
[x] No
```

Nightly Build Fix: Adding entries to audit.json

---

audit.json

RDCC-3299
RDCC-3299 Corrected audit.json
```
[ ] Yes
[X] No
```

RDCC-3299 Corrected audit.json

---

build.gradle
infrastructure/terraform.tf
src/main/java/uk/gov/hmcts/reform/professionalapi/repository/IdamRepository.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/professionalapi/repository/IdamRepositoryTest.java

https://tools.hmcts.net/jira/browse/RDCC-3234
Implementing `Spring Cache` & `Caffeine` for `Bearer Token`
```
[ ] Yes
[x] No
```

RDCC-3234: implementing Spring Cache & Caffeine for Bearer Token

---

charts/rd-professional-api/values.yaml
config/owasp/suppressions.xml
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/RDCC-3507
Create a v11 Postgres DB
```
[ ] Yes
[X] No
```

RDCC-3507: Create a v11 Postgres DB - Demo

---

infrastructure/main.tf

Added postgresql_version
```
[ ] Yes
[x] No
```

Added postgresql_version

---

infrastructure/main.tf

Updating DB Secrets
```
[ ] Yes
[x] No
```

PRD PerfTest: Updating DB Secrets

---

charts/rd-professional-api/Chart.yaml
charts/rd-professional-api/values.aat.template.yaml
charts/rd-professional-api/values.yaml
infrastructure/main.tf

https://tools.hmcts.net/confluence/display/RSTR/CHG5006041+-+PRD+and+AM+Postgress+Databases+Upgrade+to+v11+Release+Implementation+Plan
```
[ ] Yes
[X] No
```

Update configurations to point to v1 DB

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-3644
Extended CVE suppression
```
[ ] Yes
[x] No
```

RDCC-3644: PRD - CVE suppression extension

---

Jenkinsfile_CNP
Jenkinsfile_nightly
build.gradle

https://tools.hmcts.net/jira/browse/RDCC-3656
Publish Jenkins Report
```
[ ] Yes
[X] No
```

Publish Jenkins Report

---

audit.json

Nightly Fix: Adding entries to audit.json
```
[ ] Yes
[x] No
```

Nightly Fix: Adding entries to audit.json

---

infrastructure/main.tf

https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1525468401
Delete v9.6 DB. Post DB migration activity
```
[ ] Yes
[X] No
```

Delete v9.6 DB

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/PaymentAccountValidator.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/PaymentAccountServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/UserAttributeServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-3730
increase mutation coverage for new PBA code
```
[ ] Yes
[x] No
```

RDCC-3730: increase mutation coverage for new PBA code

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-3782
Collating Dependabot PRs
```
[ ] Yes
[x] No
```

RDCC-3782: Collating Dependabot PRs

---

Jenkinsfile_nightly
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-3840
Enabling Fortify Scan & Extending 'oauth2-oidc-sdk' Suppression
```
[ ] Yes
[x] No
```

RDCC-3840: Enabling Fortify Scan

---

audit.json
build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java

https://tools.hmcts.net/jira/browse/RDCC-3995
Modified test case to filter the pbas whose status message is Edited by Admin
```
[ ] Yes
[x] No
```

fix: RDCC-3995 Modified test case to filter the pbas whose status message is Edited by Admin

---

audit.json

https://tools.hmcts.net/jira/browse/RDCC-3995
fix: security scan reported issue
```
[ ] Yes
[x] No
```

fix: security scan reported issue

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-4048
CVE Fixes
```
[ ] Yes
[x] No
```

RDCC-4048: CVE Fixes

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-4088
Fixing CWE - adding dependency: `name: 'spring-security-core', version: '5.6.1'`
```
[ ] Yes
[x] No
```

RDCC-4088: Fixing CWE

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalExternalUserFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/DeletePaymentAccountsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/ModifyUserRoleIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/UpdatePaymentAccountsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/DeleteUserProfilesRequestTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/UserCreationRequestTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/DxAddressResponseTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/FetchPbaByStatusResponseTest.java

https://tools.hmcts.net/jira/browse/RDCC-3455
Adding FT/IT to cover missing edge cases
```
[ ] Yes
[x] No
```

RDCC-3455: Completeness of Tests

---

src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalInternalControllerProviderTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindOrganisationsByPbaStatusTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationsWithPbaStatusResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/SuperUserResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/domain/Organisation.java
src/main/java/uk/gov/hmcts/reform/professionalapi/domain/SuperUser.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationsWithPbaStatusResponseTest.java

https://tools.hmcts.net/jira/browse/RDCC-4145
Multiple PBA: Add Super user info and Org name while retrieving PBA
```
[ ] Yes
[X] No
```

Add Super user info and Org name while retrieving PBA

---

charts/rd-professional-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-4139
Updated java chart version to 3.7.3
```
[ ] Yes
[x] No
```

fix: Updated java chart version to 3.7.3

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-4298
Collating DependaBot PRs
```
[ ] Yes
[x] No
```

RDCC-4298: Collating DependaBot PRs

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-4331
```
[ ] Yes
[X] No
```

RDCC-4331 CVE 2020-36518

---

build.gradle

https://tools.hmcts.net/jira/browse/RDCC-4380
```
[ ] Yes
[X] No
```

RDCC-4380 CVE Fix

---

Dockerfile
build.gradle
docker-compose.yml

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-4235
Java 17 Migration for Professional Reference Data
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No

FEAT: Java 17 upgrade

---

audit.json

https://tools.hmcts.net/jira/browse/RDCC-4468
Adding Entries to audit.json
```
[ ] Yes
[x] No
```

RDCC-4468: Nightly Fix - Adding Entries to audit.json

---

build.gradle

CVE Fix for Spring Core
```
[ ] Yes
[X] No
```

CVE Fix for SpringCore

---

src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/AddContactInformationToOrganisationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrgWithContactInformationDxAddress.java
src/integrationTest/resources/db/migration/V10__alter_dx_exchange.sql
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidator.java
src/main/resources/db/migration/V10__alter_dx_exchange.sql
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidatorTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/domain/DxAddressTest.java

https://tools.hmcts.net/jira/browse/RDCC-4576
Increase Size Constraint of DX Exchange from `20` to `40`
```
[ ] Yes
[x] No
```

RDCC-4576: Increase Size Constraint of DX Exchange

---

build.gradle

CVE Fix for launchdarkly sdk java
```
[ ] Yes
[ X] No
```

CVE Fix for LaunchDarklySDK

---

build.gradle

CVE Fix for Tomcat embed 
```
[ ] Yes
[X] No
```

CVE Fix for Tomcat Embed Core n websocket

---

renovate.json

https://tools.hmcts.net/jira/browse/RDCC-4819
Configured renovate
```
[ ] Yes
[x] No
```

config: RDCC-4819 Configured renovate

---

.github/workflows/combine-prs.yml

https://tools.hmcts.net/jira/browse/RDCC-4856
```
[ ] Yes
[X] No
```

RDCC-4856:PRD API Automerge Renovate PR's

---

audit.json

https://tools.hmcts.net/jira/browse/RDCC-4939
Nightly Build Fix - adding entry to `audit.json`
```
[ ] Yes
[x] No
```

RDCC-4939: Nightly Build Fix - adding entry to `audit.json`

---

.github/dependabot.yml

https://tools.hmcts.net/jira/browse/RDCC-4944
Deleted dependabot yaml file as Renovate changes are already in place to upgrade the dependencies automatically
```
[ ] Yes
[x] No
```

RDCC-4944 Delete dependabot yaml file

---

audit.json

https://tools.hmcts.net/jira/browse/RDCC-4967
Nightly Build Fix - adding entries to `audit.json` 
```
[ ] Yes
[x] No
```

RDCC-4967: Nightly Build Fix - adding entries to `audit.json`

---

audit.json

https://tools.hmcts.net/jira/browse/RDCC-5023
Nightly Build Fix - adding entries to `audit.json`
```
[ ] Yes
[x] No
```

RDCC-5023: Nightly Build Fix - adding entries to `audit.json`

---

charts/rd-professional-api/Chart.yaml
charts/rd-professional-api/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/RDCC-5047
Upgrade java chart 
```
[ ] Yes
[x] No
```

RDCC-5047 Upgrade java chart 

---

audit.json

https://tools.hmcts.net/jira/browse/RDCC-5152
Adding entry to `audit.json`
```
[ ] Yes
[x] No
```

RDCC-5152: Adding entry to `audit.json`

---

config/owasp/suppressions.xml

Address CVE-2021-28170

---

src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalExternalControllerProviderTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/AddPaymentAccountsIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java

https://tools.hmcts.net/jira/browse/RDCC-5082
Populating Pending PBAs List for Get PBA by Email APIs (Internal and External)
```
[ ] Yes
[x] No
```

RDCC-5082: Populating Pending PBAs List for Get PBA by Email APIs

---

audit.json

https://tools.hmcts.net/jira/browse/RDCC-5216
Adding Entries to `audit.json` to fix Security Scan
```
[ ] Yes
[x] No
```

RDCC-5216: Adding Entries to `audit.json` to fix Security Scan

---

build.gradle
src/main/java/uk/gov/hmcts/reform/professionalapi/util/JsonFeignResponseUtil.java

Transfer Encoding
```
[ ] Yes
[X] No
```

Remove Transfer encoding

---

Jenkinsfile_CNP

Hack to push through the images and chart on master

---

Dockerfile

Use latest agent

---

build.gradle

upgrade feign client

---

audit.json

Add Security Scan Entry for new functionality pagination in retrieveorg
```
[ ] Yes
[X] No
```

Add Entry in to audit.json to resolve security scan issues

---

audit.json

https://tools.hmcts.net/jira/browse/RDCC-5801
Nightly Fix - Adding entries to `audit.json`
```
[ ] Yes
[x] No
```

RDCC-5801: Nightly Fix - Adding entries to `audit.json`

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/advice/ExceptionMapper.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/DxAddressCreationRequest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/OrganisationCreationRequestValidator.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationStatusValidatorImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponse.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/advice/UnauthorizedExceptionTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java

Reverts hmcts/rd-professional-api#1328

Revert "RDCC-5592:rd-professional-api code smell issues fixes"

---

build.gradle

CVE for PostGreSQL version
[ ] Yes
[X] No

CVE Fix for postgresql

---

Jenkinsfile_CNP
Jenkinsfile_nightly
charts/rd-professional-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-5931
Replace after with afterSuccess in all RD Repos
```
[ ] Yes
[X] No
```

Replace after with afterSuccess for deprecation : RDCC-5931

---

charts/rd-professional-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-1707
Upgraded helm chart version to `4.0.11`
```
[ ] Yes
[x] No
```

RDCC-1707: Upgrade helm chart version to latest

---

charts/rd-professional-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RDCC-6374
Upgrading chart version to `4.0.13`
```
[ ] Yes
[x] No
```

RDCC-6374: Upgrading chart version to latest

---

.github/renovate.json
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-6421
Added renovate.json
```
[ ] Yes
[x No
```

RDCC-6421 Added renovate.json

---

Dockerfile
build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/docs/SwaggerPublisher.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/JwtDecoderMockBuilder.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/KeyGenUtil.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/SpringBootIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/reform/professionalapi/configuration/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/WelcomeController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationMfaStatusController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/DxAddressCreationRequest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/oidc/JwtGrantedAuthoritiesConverter.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalControllerTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/oidc/JwtGrantedAuthoritiesConverterTest.java

https://tools.hmcts.net/jira/browse/RDCC-6249
Spring boot upgrade to 2.7.7
```
[ ] Yes
[x] No
```

Spring boot upgrade 2.7.7

---

audit.json

Audit.json entry
```
[ ] Yes
[X] No
```

security audit.json entry

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-6430
fix- CVE fixes in professional Reference Data
```
[ ] Yes
[ X] No
```

fix- CVE fixes in professional Reference Data

---

src/main/java/uk/gov/hmcts/reform/professionalapi/controller/WelcomeController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationExternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/OrganisationMfaStatusController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/external/ProfessionalExternalUserController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/ProfessionalUserInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/DxAddressCreationRequest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/validator/impl/OrganisationStatusValidatorImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationEntityResponse.java
src/main/java/uk/gov/hmcts/reform/professionalapi/oidc/JwtGrantedAuthoritiesConverter.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/advice/UnauthorizedExceptionTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-6548
Addressing Sonar Issues
```
[ ] Yes
[x] No
```

RDCC-6548: Addressing Sonar Issues

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSRD-162
Upped spring framework to fix CVE-2023-20860
```
[ ] Yes
[x] No
```

Upped spring framework to fix CVE-2023-20860

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSRD-249
set max heap size for tests
```
[ ] Yes
[x] No
```

DTSRD-249: set max heap size for tests

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSRD-47
Removed suppressions for remedied CVEs
```
[ ] Yes
[x] No
```

remove suppressions

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/domain/OrganisationStatus.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-6780
[RDCC-6780]add sorting in organisation list
```
[ ] Yes
[ x] No
```

[RDCC-6780]add sorting in organisation list

---

src/main/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtil.java

https://tools.hmcts.net/jira/browse/DTSRD-260
NPE when handling ErrorResponse in RefDataUtil
```
[ ] Yes
[x] No
```

DTSRD-260: NPE when handling ErrorResponse in RefDataUtil

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDCC-6780
[RDCC-6780]CVE fix
```
[ ] Yes
[ x] No
```

[RDCC-6780]CVE fix

---

src/test/java/uk/gov/hmcts/reform/professionalapi/domain/ProfessionalUserTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/FeatureToggleServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-6888
[RDCC-6888]Increase Mutation Coverage for Professional API
```
[ ] Yes
[x ] No
```

[RDCC-6888]Increase Mutation Coverage for Professional API

---

build.gradle
config/owasp/suppressions.xml

CVE suppression CVE-2023-34034

---

config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/UpdateOrganisationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/SuperController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerV2.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/request/OrganisationOtherOrgsCreationRequest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/repository/OrgAttributeRepository.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationService.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalControllerV2Test.java
src/test/java/uk/gov/hmcts/reform/professionalapi/helper/OrganisationFixtures.java

https://tools.hmcts.net/jira/browse/RDCC-6841
PRD - update org API changes to store other organisation details
```
[ ] Yes
[x ] No
```

PRD - update org API changes to store other organisation details

---

src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/PaymentAccountServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/UserAttributeServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtilTest.java

https://tools.hmcts.net/jira/browse/RDCC-6962
[RDCC-6962]PRD - Increase Mutation Coverage for other organisation development
```
[ ] Yes
[ x] No
```

[RDCC-6962]PRD - Increase Mutation Coverage for other organisation development

---

README.md
config/owasp/suppressions.xml

NA
Change pact broker portal tag
```
[ ] Yes
[ x] No
```

Change pact broker portal tag

---

config/owasp/suppressions.xml
src/main/resources/db/migration/V12__create_bulk_customer_details.sql

https://tools.hmcts.net/jira/browse/RDCC-7020
[RDCC-7020]PRD: Create new table for Bulk Customer Details
```
[ ] Yes
[ x] No
```

[RDCC-7020]PRD: Create new table for Bulk Customer Details

---

build.gradle
config/owasp/suppressions.xml

DTSRD-1189
```
[ ] Yes
[ *] No
```

DTSRD- 1189

---

audit.json
config/owasp/suppressions.xml

DTSRD-1173
fixing Zaproxy error
```
[ ] Yes
[* ] No
```

DTSRD-1173-1

---

build.gradle
charts/rd-professional-api/Chart.yaml

- Updating netty versions to resolve CVE-2023-4586.
https://tools.hmcts.net/jira/browse/DTSRD-1456
Updating netty dependencySet to higher version to resolve CVE.

DTSRD-1456

---

Jenkinsfile_CNP

* DTSRD-1017.commit suppression
* DTSRD-1239.Remove branches to sync -professional demo and master

DTSRD-1466.Remove branches to sync -location demo 

---

Jenkinsfile_CNP
infrastructure/main.tf
infrastructure/output.tf
infrastructure/terraform.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/DTSRD-1242

DTSRD-1242.Upgrade to postgres V15 . - merge demo to perftest

---

src/test/java/uk/gov/hmcts/reform/professionalapi/domain/SingletonOrgTypeTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-7029
PRD: increase code coverage, mutation coverage for PRD
- [ x] Does this PR introduce a breaking change

[RDCC-7029]PRD: increase code coverage, mutation coverage for PRD

---

Jenkinsfile_CNP
infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf

* DTSRD-1017.commit suppression
* DTSRD-1241.merging v15 changes to ithc and perftest branches

DTSRD-1241.merging v15 changes to ithc and perftest branches (#1474)

---

config/owasp/suppressions.xml

suppress CVE-2023-5590

---

src/main/resources/application.yaml

DTSRD-1242.adding schema name to connection string

---

src/main/resources/application.yaml

Update application.yaml. reverting changes to connection string

---

config/owasp/suppressions.xml
src/main/resources/application.yaml

DTSRD-1466.Updating schema parameter with hibernate

---

src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalInternalControllerProviderTest.java

https://tools.hmcts.net/jira/browse/RDCC-7097
[RDCC-7097]UP : Consumer Pact Test Cases needs to be added
- [ x] Does this PR introduce a breaking change

[RDCC-7097]UP : Consumer Pact Test Cases needs to be added

---

src/main/resources/application.yaml

default_schema change

---

src/integrationTest/resources/application.yml
src/main/resources/application.yaml
src/test/resources/application.yml

Perftest issue

---

docker-compose.yml

Taking the latest change from master

---

Jenkinsfile_CNP
infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf

DTSRD-1239. adding V15 details to demo

---

infrastructure/prod.tfvars
src/main/resources/application.yaml

SKU Increase

---

charts/rd-professional-api/values.aat.template.yaml

Increase resources for AAT staging

---

Jenkinsfile_CNP
charts/rd-professional-api/values.aat.template.yaml
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/terraform.tf
infrastructure/variables.tf
src/main/resources/application.yaml

Dtsrd 1241- adding v15 ti ithc

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDCC-7244
Register Org : Update the Org Deletion logic in V1 API.
- [X ] Does this PR introduce a breaking change

Delete organisation with the user attributes as well

---

src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/CreateOrgWithOtherOrg.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindPaymentAccountsByEmailTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/UpdateOrganisationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java

https://tools.hmcts.net/jira/browse/RDCC-7205

Register Org : Integration Test Cases-Otherorgregistration

---

deletescript/sql/delete-functional-test-data.sql
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java

DTSRD-1873: Clean test data

---

src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/UpdateOrganisationTest.java
src/test/java/uk/gov/hmcts/reform/professionalapi/helper/OrganisationFixtures.java

https://tools.hmcts.net/jira/browse/RDCC-7205

testcase for Othergovernment

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/RetrieveOrganisationsTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/constants/ProfessionalApiConstants.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/internal/OrganisationInternalController.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/OrganisationService.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImpl.java
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/OrganisationServiceImplTest.java

DTSRD-1886: internal endpoint to retrieve organisation details

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java

DTSRD-1886: ignored failed functional test

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java

https://tools.hmcts.net/jira/browse/DTSRD-1886

DTSRD-1886: fix for failing functional test assertion

---

src/integrationTest/resources/db/migration/V20__alter_contact_informatin.sql
src/main/java/uk/gov/hmcts/reform/professionalapi/domain/ContactInformation.java
src/main/resources/db/migration/V20__alter_contact_informatin.sql

DTSRD-1934: PRD-Modify addressLine2 DB column length

---

Jenkinsfile_CNP
infrastructure/main.tf
infrastructure/terraform.tf
infrastructure/variables.tf
src/integrationTest/resources/application.yml

DTSRD-1893-1.Upgrading main branch to V16 and adding subnet_suffix

---

README.md
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/BulkCivilApiFunctionalTest.java
src/functionalTest/resources/application-functional-bulkcustomer.yaml
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/BulKCustmerDetailsAPITest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/ProfessionalReferenceDataClient.java
src/main/java/uk/gov/hmcts/reform/professionalapi/repository/BulkCustomerDetailsRepository.java

CIVIL Bulk customer Test cases

---

infrastructure/main.tf
infrastructure/variables.tf
src/integrationTest/resources/application.yml

Dtsrd 1234.Adding force_user_permissions_trigger to get DTS CFT DB Access Reader access

---

infrastructure/main.tf
infrastructure/variables.tf
src/integrationTest/resources/application.yml

DTSRD-2065.Adding force_user_permissions_trigger to get access to DTS JIT Access rd DB Reader SC user

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalExternalUserFunctionalTest.java

https://tools.hmcts.net/jira/browse/GA-97

Added functional test code for GA-97

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalExternalUserFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/util/AuthorizationEnabledIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImpl.java
src/main/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtil.java
src/test/java/uk/gov/hmcts/reform/professionalapi/util/RefDataUtilTest.java

DTSRD-2103: Sorting of Active Orgs Users

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java

GA-43 Added fix for date format issue

---

build.gradle

Change mutationThreshold to 80

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/AuthorizationFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalForV2ApiTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/util/DateUtils.java

Added functional test for GA-43 and refactored GA-25 functional test

Added functional test for GA-43 and refactored GA-25 functional test

---

src/main/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/professionalapi/service/impl/ProfessionalUserServiceImplTest.java
src/test/resources/application.yml

https://tools.hmcts.net/jira/browse/GA-169

GA-169: use orgType

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalExternalUserFunctionalForV2ApiTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalForV2ApiTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java

GA-117 Added functional test and refactored existing functional test

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalForV2ApiTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/client/ProfessionalApiClient.java

Added functional test for GA-126

---

src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalForV2ApiTest.java
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalInternalUserFunctionalTest.java

Ga 126 qa3

---

infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/variables.tf
src/integrationTest/resources/application.yml

DTSRD-2065-3.SCHEMA OWNER FIX

---

src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/ProfessionalUserInternalControllerV2ProviderTest.java
src/integrationTest/java/uk/gov/hmcts/reform/professionalapi/FindUsersByOrganisationsIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/professionalapi/controller/response/OrganisationUserResponse.java

[GA-207](https://tools.hmcts.net/jira/browse/GA-207)
Add deleted field to `OrganisationUserResponse.java`

GA-207 add deleted field to the user response

---

charts/rd-professional-api/Chart.yaml
charts/rd-professional-api/values.yaml

DTSRD-2442: PI33 Configure spot instances in non-production

---

charts/rd-professional-api/Chart.yaml

DTSRD-2525: Upgrade Chart Java version

---

infrastructure/main.tf
src/integrationTest/resources/application.yml

Fix ownership and db access

---

build.gradle

DTSRD-2525: fix flyway migration issue

---

src/integrationTest/resources/application.yml
src/main/resources/application.yaml

DTSRD-2525: handle flyway out of order

---

infrastructure/main.tf
infrastructure/perftest.tfvars
infrastructure/variables.tf

DTSRD-2845: Resize PG flexible server instance to match V11

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
gradle/wrapper/gradle-wrapper.properties
gradlew
src/contractTest/java/uk/gov/hmcts/reform/professionalapi/provider/OrganisationalInternalControllerProviderTest.java
src/main/resources/testcontainers.properties

https://tools.hmcts.net/jira/browse/DTSRD-3041

DTSRD-3041

---

build.gradle

Update build.gradle Fix build

---

build.gradle

Update build.gradle - Fixing Nightly build fail

---

Dockerfile
build.gradle

DTSRD-87: address flyway migration issue

---

build.gradle
database/Dockerfile

Update build.gradle -revert flyway version

---

Jenkinsfile_CNP
Jenkinsfile_nightly
src/functionalTest/java/uk/gov/hmcts/reform/professionalapi/ProfessionalExternalUserFunctionalForV2ApiTest.java

https://tools.hmcts.net/jira/browse/DTSRD-3580
Jenkins Test Reports to Publish on Failure

DTSRD-3580 Jenkins Test Reports to Publish on Failure

---

charts/rd-professional-api/Chart.yaml
charts/rd-professional-api/values.yaml

Dummy space update to trigger build

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/CME-251
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change

CME-251: Disable sync to ITHC for database monitoring testing

---

Jenkinsfile_CNP
infrastructure/main.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/CME-251
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change

CME-251: Database monitoring and alerting on RD repositories

---

infrastructure/terraform.tf

https://tools.hmcts.net/jira/browse/CME-294
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
- [x ] Does this PR introduce a breaking change

CME-294: Update azurerm

---

build.gradle

Restore HMCTS java plugin 0.12.63

Fix for build failure

---

charts/rd-professional-api/Chart.yaml

RefData Helm OCI Update - rd-professional-api

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CME-610
Remove not needed CVE suppressions

CME-610 remove not needed CVE suppressions
